
imagePullPolicy: "IfNotPresent"
vault:
  authType: "TOKEN"
  image: "vault"
  imageTag: "0.6.5"
  cpu: "50m"
  memory: "200Mi"
  domain: vault.yourproject.com
  email: test@example.com
vaultui:
  image: "djenriquez/vault-ui"
  imageTag: "latest"
  cpu: "50m"
  memory: "250Mi"
  domain: vault-ui.yourproject.com
gcs:
  # Fill in these values via --set
  # Values can be obtained by generating
  # a new service account in the GCP console.
  bucketName: "<SOME_BUCKET_NAME>"
  client_email: "<SOME_CLIENT_EMAIL>"
  client_id: "<CLIENT_ID>"
  client_x509_cert_url: "<CLIENT_X509_CERT_URL>"
  project_id: "<PROJECT_ID>"
  private_key_id: "<PRIVATE_KEY_ID>"
  private_key: <PRIVATE_KEY>